
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 05 14:18:35 PST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 15;
  public static final int AND = 5;
  public static final int OR = 6;
  public static final int IGUAL = 8;
  public static final int MENORIGUAL = 13;
  public static final int DECIMAL = 4;
  public static final int NOT = 7;
  public static final int MAYORQUE = 10;
  public static final int POT = 18;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int DIFERENTE = 9;
  public static final int DIV = 17;
  public static final int MENORQUE = 11;
  public static final int PAR_IZQ = 19;
  public static final int MAYORIGUAL = 12;
  public static final int error = 1;
  public static final int PAR_DER = 20;
  public static final int ENTERO = 3;
  public static final int MAS = 14;
}

